
$font = FiraCode Nerd Font,FiraCode Nerd Font Med

background {
    monitor =
    path = screenshot # "~/wallpapers/wallhaven-e7821r_2560x1440.png"
    blur_passes = 4 
    blur_size = 6
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgb(ffffff)
    inner_color = rgb(222222)
    font_color = rgb(ffffff)
    fade_on_empty = false
    placeholder_text = Input password...
    fail_text = $PAMFAIL$FPRINTFAIL
    font_family = $font 
    hide_input = false
    position = 0, -80
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME12
    font_size = 64
    font_family = $font 
    position = 0, 80
    halign = center
    valign = center
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y" # update every 60 seconds
    font_size = 25
    font_family = $font

    position = 0, 0
    halign = center
    valign = center
}

