[mgr]
show_hidden = true

[opener]
vscode = [
    { run = 'code "$1"', orphan = true, desc = "VS Code" }
]
cursor = [
    { run = 'cursor "$1"', orphan = true, desc = "Cursor" }
]
vim = [
    { run = 'vim "$1"', orphan = true, desc = "Vim"}
]

preview = [
    { run = 'open -a Preview "$1"', orphan = true, desc = "Preview"}
]

[open]
prepend_rules = [
    { url = "*/", use = [ "vscode", "cursor" ] },
    { url = "*.pdf", use = [ "preview" ] }
]
append_rules = [
	{ url = "*", use = "vim" },
]
